diff a/Dockerfile b/Dockerfile	(rejected hunks)
@@ -1,31 +1,30 @@
 # vim:set ft=dockerfile:
 FROM continuumio/miniconda3
-MAINTAINER https://github.com/bird-house/emu
+ARG DEBIAN_FRONTEND=noninteractive
+ENV PIP_ROOT_USER_ACTION=ignore
+LABEL org.opencontainers.image.authors=https://github.com/bird-house/emu
 LABEL Description="Emu WPS" Vendor="Birdhouse" Version="0.13.0"

-# Update Debian system
-RUN apt-get update && apt-get install -y \
- build-essential \
-&& rm -rf /var/lib/apt/lists/*
+# Set the working directory to /code
+WORKDIR /code

-# Update conda
-RUN conda update -n base conda
+# Create conda environment
+COPY environment.yml .
+RUN conda env create -n Emu -f environment.yml && conda install -n Emu gunicorn && conda clean --all --yes

-# Copy WPS project
-COPY . /opt/wps
-
-WORKDIR /opt/wps
+# Add the project conda environment to the path
+ENV PATH=/opt/conda/envs/Emu/bin:$PATH

-# Create conda environment with PyWPS
-RUN ["conda", "env", "create", "-n", "wps", "-f", "environment.yml"]
+# Copy WPS project
+COPY . /code

-# Install WPS
-RUN ["/bin/bash", "-c", "source activate wps && pip install -e ."]
+# Install WPS project
+RUN pip install . --no-deps

 # Start WPS service on port 5000 on 0.0.0.0
 EXPOSE 5000
-ENTRYPOINT ["/bin/bash", "-c"]
-CMD ["source activate wps && exec emu start -b 0.0.0.0 -c /opt/wps/etc/demo.cfg"]
+
+CMD ["gunicorn", "--bind=0.0.0.0:5000", "emu.wsgi:application"]

 # docker build -t bird-house/emu .
 # docker run -p 5000:5000 bird-house/emu
