# conda env create -f environment-docs.yml
name: emu-docs
channels:
- conda-forge
- defaults
dependencies:
# restore once an official pywps release contain the fix
#- pywps>=4.2
- sphinx
- nbsphinx
- ipython
- pip
- pip:
  # delete once an official pywps release contain this fix, also delete in Makefile
  - https://github.com/Ouranosinc/pywps/archive/2a55b6e95f51c648dc94bf3c89db7370b56c1c9c.zip
