name: emu-docker
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.15
  - click >=8.3.0
  - defusedxml
  - geomet
  - jinja2 >=3.1.6
  - netcdf4
  - pandas
  - psutil >=7.2.0
  - pywps >=4.5.2,<4.7.0
  - xarray <2026.04.0
  - zarr <3.0
  # Needed for some reason
  - pytest >=9.0.2
